### ISSUE TITLE
404 Error with DDEV based TYPO3 13 installation

### ISSUE THREAD

**Issue by pdehne** [s2b/ddev-vite-sidecar#11]
The TYPO3 website I am developing can be reached locally using https://keb-bc-slg.de.ddev.site:8443/ without problems. But when I start the Vite development server using `ddev vite` and try to reach the website using https://vite.keb-bc-slg.de.ddev.site:8443/ I get an 404 error:

```
❯ curl -k --verbose https://vite.keb-bc-slg.de.ddev.site:8443/
* Host vite.keb-bc-slg.de.ddev.site:8443 was resolved.
* IPv6: (none)
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:8443...
* Connected to vite.keb-bc-slg.de.ddev.site (127.0.0.1) port 8443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.x
> GET / HTTP/1.1
> Host: vite.keb-bc-slg.de.ddev.site:8443
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< Content-Length: 0
< Date: Wed, 23 Oct 2024 10:57:23 GMT
< Server: Apache/2.4.62 (Debian)
<
* Connection #0 to host vite.keb-bc-slg.de.ddev.site left intact
```

If I stop the `ddev vite` command and try to reach the website again using `https://vite.keb-bc-slg.de.ddev.site:8443/` I get the `vite-server-not-running.html` response. So the request is at least reaching the proxy (https://github.com/s2b/ddev-vite-sidecar/blob/main/apache/vite.conf) that should forward the request to the Vite development server:

```
❯ curl -k --verbose https://vite.keb-bc-slg.de.ddev.site:8443/
* Host vite.keb-bc-slg.de.ddev.site:8443 was resolved.
* IPv6: (none)
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:8443...
* Connected to vite.keb-bc-slg.de.ddev.site (127.0.0.1) port 8443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.x
> GET / HTTP/1.1
> Host: vite.keb-bc-slg.de.ddev.site:8443
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 503 Service Unavailable
< Accept-Ranges: bytes
< Content-Length: 1389
< Content-Type: text/html
< Date: Wed, 23 Oct 2024 10:58:12 GMT
< Etag: "56d-6250d8d687690"
< Last-Modified: Tue, 22 Oct 2024 09:39:57 GMT
< Server: Apache/2.4.62 (Debian)
<
<!DOCTYPE html>
<html lang="en">
...
</html>
```

I stripped down my `vite.config.js` to the very basic, the Vite development server needs only to proxy all requests to the TYPO3 website:

```
export default defineConfig({
  server: {
    host: "0.0.0.0",
    origin: "https://vite.keb-bc-slg.de.ddev.site:8443",
  }
});
```

Do you an idea why I do get a 404 error through the Vite development server?

**Comment by rfay** [comment]
If you could do a `ddev debug test` and put it as a gist in gist.github.com we'd know more about your project and what you're trying to do.  If you could show the top of your .ddev/config.yaml (before the comments) that would help too.

**Comment by pdehne** [comment]
Many thanks for taking a look!

Sure here is the gist: [ddev debug test](https://gist.github.com/pdehne/039bf58ac4a7a33230d4679d66cfe0a3).

Here is the `ddev/config.yaml`:
```
name: keb-bc-slg.de
type: typo3
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
router_http_port: "8090"
router_https_port: "8443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
webimage_extra_packages: [graphicsmagick, poppler-utils, catdoc, unrtf]
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2"
web_environment:
    - TYPO3_CONTEXT=Development
corepack_enable: false
```

Also the `config.vite.yaml`, just in case it is relevant:
```
#ddev-generated
additional_hostnames:
  - vite.keb-bc-slg.de
web_environment:
  - VITE_SERVER_URI=https://vite.keb-bc-slg.de.ddev.site
  - VITE_PACKAGE_MANAGER=npm
```
